### ISSUE TITLE
Unable to execute simple cluster commands using ClusterClient when slave_ok=True

### ISSUE THREAD

**Issue by MaryRosariaTaft** [schlitzered/pyredis#5]
I have a Redis Cluster with 9 instances—3 masters and 6 slaves.  I want to connect pyredis to this cluster and execute simple commands like `get` and `set`.  Without informing pyredis of any of the slave nodes, this works fine.  For example:

`cc = ClusterClient(seeds=[("master1_ip",6379), ("master2_ip",6379), ("master3_ip",6379)], slave_ok=False)`
`cc.set("key", "value")`

correctly sets "key" to "value" on the appropriate master instance.  Furthermore, even if I list all the instances, as long as `slave_ok` is still `False`, `get` and `set` seem to behave correctly.  For example:

`cc = ClusterClient(seeds=[("master1_ip",6379), ("master2_ip",6379), ("master3_ip",6379), ("slave1_ip",6380), ("slave2_ip",6380), ("slave3_ip",6380), ("slave4_ip",6381), ("slave5_ip",6381), ("slave6_ip",6381)], slave_ok=False)`
`cc.get("key")`

will similarly correctly get the value at "key".  However, as soon as I toggle `slave_ok` to `True` in either of the above examples (with or without listing the slave instances in `seeds`—I'm also not sure which form is correct), I get the following error:

`pyredis.exceptions.PyRedisError: Slot moved to often or wrong shard_key, giving up,`

and the `get` or `set` request is never processed by the cluster.  It seems, at least, that requests are _hitting_ the cluster, because preceding the above `PyRedisError`, I see errors of the form `pyredis.exceptions.ReplyError: MOVED (hashslot) (ip):(port)`—this seems like a response from the cluster telling pyredis that it should redirect a request from one instance/shard to another.

I'm curious as to the cause of this error.  And furthermore, what does the `slave_ok` option actually do/change?  I thought that enabling it might allow me to do something like direct `set`s to masters and `get`s to slaves, but I can't find any description other than "Set to True if this Client should use slave nodes" in the documentation.

Thank you.

**Comment by schlitzered** [comment]
if you create a instance of ClusterClient, with slave_ok=true, the client will always use slave instances. so commands trying to write will always fail, but read commands should work.

also the parameter "seeds" only needs some "seed" nodes, the ClusterClient will then get a list of all master and slave nodes belonging to the cluster from the seed node.

can you please confirm that also read commands like "get" will not work with "slave_ok=true"?

**Comment by schlitzered** [comment]
i just tried it myself and found this:

https://redis.io/topics/cluster-spec#scaling-reads-using-slave-nodes

you have to execute for each connection to each slave a "READONLY" command, which will inform a redis slave to accept read requests. otherwise the slave will always answer with a redirect message, which points to the responsible master instance.

it would make sense to enhance pyredis to automatically do this. i will take a look into this next week.

**Comment by schlitzered** [comment]
I updated the client in the master branch, but did not yet issue a new release.

if "slave_ok=True" the READONLY command will be send to ClusterClient and ClusterPool Connections.

Remember that slave_ok will always connect to slave instances, executing a write command will still fail with the above error message.

could you please give it a try?

**Comment by MaryRosariaTaft** [comment]
Thank you so much for following up!

I think I understand better: so, if `slave_ok=False` then the client  only communicates with master instances, but if `slave_ok=True` then it only communicates with slave instances—is that correct?

After adding your updates the client seems to perform as expected: if I create a ClusterClient with `slave_ok=False` then `get` and `set` both work; if `slave_ok=True` then `get` works and `set` fails with the same error message as before.

**Comment by schlitzered** [comment]
> I think I understand better: so, if slave_ok=False then the client only communicates with master instances, but if slave_ok=True then it only communicates with slave instances—is that correct?

yes, this is correct.

> After adding your updates the client seems to perform as expected: if I create a ClusterClient with slave_ok=False then get and set both work; if slave_ok=True then get works and set fails with the same error message as before.

this is also expected, you should not send commands to a slave instance, that will modify data.

if you need to read from slaves, and write to master instances, i would suggest to create two ClusterClient objects, one in with slave_ok=False, and one with slave_ok=True.

while technically the client library could be extended to distinguish between read and write requests, and automatically send read/write requests to the appropriate redis server for simple commands. makeing this work for transactions, or lua scripts would be pretty hard. so i would suggest to simply make the decision within the application.

or what is your opinion?
