### ISSUE TITLE
crc16 is not supported ?

### ISSUE THREAD

**Issue by rajivmucheli** [schlitzered/pyredis#8]
Hi,

Thanks for the great package, we are using this for rate-limiting application. Due to advancements in other packages, this version is incompatible. I get the below error :

Building wheel for crc16 (setup.py): started
>   Building wheel for crc16 (setup.py): finished with status 'error'
>   error: subprocess-exited-with-error
>   
>   × python setup.py bdist_wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [17 lines of output]
>       running bdist_wheel
>       running build
>       running build_py
>       Generating grammar tables from /usr/lib/python3.10/lib2to3/Grammar.txt
>       Generating grammar tables from /usr/lib/python3.10/lib2to3/PatternGrammar.txt
>       creating build
>       creating build/lib.linux-x86_64-3.10
>       creating build/lib.linux-x86_64-3.10/crc16
>       copying python3x/crc16/__init__.py -> build/lib.linux-x86_64-3.10/crc16
>       copying python3x/crc16/test.py -> build/lib.linux-x86_64-3.10/crc16
>       copying python3x/crc16/crc16pure.py -> build/lib.linux-x86_64-3.10/crc16
>       running build_ext
>       building 'crc16._crc16' extension
>       creating build/temp.linux-x86_64-3.10
>       creating build/temp.linux-x86_64-3.10/src
>       x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.10 -I/var/lib/openstack/include/python3.10 -c src/_crc16module.c -o build/temp.linux-x86_64-3.10/src/_crc16module.o
>       error: command 'x86_64-linux-gnu-gcc' failed: No such file or directory
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for crc16
>   Running setup.py clean for crc16
> Successfully built raven watcher-middleware audit-middleware rate-limit-middleware glance_store
> Failed to build crc16
> 64.88 ERROR: Could not build wheels for crc16, which is required to install pyproject.toml-based projects
> ERROR: process "/bin/sh -c /opt/loci/scripts/install.sh" did not complete successfully: exit code: 1

Could you please provide a fix ?

Regards,
Rajiv

**Comment by schlitzered** [comment]
can you give the branch from the pr a try?
